name: psique_eleve
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.10.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  dio: ^4.0.4
  hive: ^2.1.0
  path_provider: ^2.0.9
  supabase_flutter: ^0.2.12
  google_fonts: ^2.3.1
  cpf_cnpj_validator: ^2.0.0
  string_validator: ^0.3.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  modular_test: ^1.0.1+1
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/png/
